name: 'disc_golf_dbt'
version: '1.0.0'
config-version: 2

profile: 'disc_golf_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  disc_golf_dbt:
    staging:
      +materialized: table
      +schema: staging
    dimensional:
      +materialized: table
      +schema: dw
    analytics:
      +materialized: table
      +schema: analytics

on-run-end:
  - "{{ create_constraints() }}"
